name: Java CI with Maven

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        # Set up maven repository credentials for highmed-dsf dependencies
        server-id: highmed-dsf
        server-username: USERNAME
        server-password: GITHUB_TOKEN

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: |
          ~/.m2/repository
        key: maven-repo

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USENAME: ${{ github.actor }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
